# Project information

site_name: My Wiki

# Repository
repo_name: 'hiimmazl/hiimmazl.github.io'
repo_url: 'https://github.com/hiimmazl/hiimmazl.github.io'

# Configuration
theme:
  name: 'material'
  
  logo:
    icon: 'school'

  #favicon: 'assets/images/favicon.ico'
    
  language: 'en'
  
  feature:
    tabs: true
    
# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
  - Specimen: specimen.md
  - Customization: customization.md
  - Compliance with GDPR: compliance.md
  - Release notes: release-notes.md
  - Author's notes: authors-notes.md
  - Contributing: contributing.md
  - License: license.md
